---
- name: update packages
  yum:
    name: '*'
    state: latest
  tags: [update_pkd]

# Apache Intallationn
- name: install httpd
  yum:
    name: httpd
    state: present
    notify: Restart httpd
  tags: [install_httpd]

# MariaDB Intallation
- name: Add official MariaDB repository
  yum_repository:
    name: MariaDB
    baseurl: "http://{{ mariadb_mirror }}/{{ mariadb_version }}/{{ ansible_distribution|lower|regex_replace('redhat', 'rhel')|regex_replace('oraclelinux', 'centos') }}{{ ansible_distribution_major_version }}-amd64"
    gpgkey: https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
    gpgcheck: true
  tags: [mariadb]

- name: Install mariadb
  yum:
          name: "{{ item }}"
          state: latest
  loop:
          - " mariadb-server "
          - " mariadb " 
  notify: Restart mariadb
  tags: [install_mariadb]
# MySQL Configuration
- name: Set root user password
  mysql_user: 
    name: root
    host: "{{ item }}"
    password: "{{ mysql_root_password }}"
    check_implicit_admin: yes
    login_user: root
    login_password: "{{ mysql_root_password }}"
    state: present
  tags: [set_root_pass]
- name: Removes the MySQL test database
    mysql_db:
      name: test
      state: absent
      login_user: root
      login_password: "{{ mysql_root_password }}"
    tags: [remove_test_database]
- name: remove remote root
    mysql_user:
      check_implicit_admin: true
      login_user: root
      login_password: "{{ mysql_root_password }}"
      user: root
      host: "{{ lamp_fqdn }}"
      state: absent  
  tags: [remove_remote_root]
# PHP Intallation
- name: Install php
  yum:
          name: "{{ item }}"
          state: latest
  loop:
          - " php "
          - " php-mysql " 
          - " php-fpm"
  notify: Restart httpd
  tags: [install_php]
# PHP Info Page
- name: Copy info.php
  copy:
    src: info.php
    dest: /var/www/html/info.php
  tags: [php-info]
