---
- name: Restart httpd
  service:
    name: httpd
    state: restarted
    enabled: yes
  tags: [restart_httpd]
- name: Restart mariadb
  service:
    name: mariadb
    state: restarted
    enabled: yes
  tags: [restart_mariadb]